config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'users/follow'
  get 'users/unfollow'
  get 'home/index'
  devise_for :users
  resources :users, only: [:index, :show] do
    member do
      post 'follow'
      delete 'unfollow'
      get 'profile'
    end
  end
  resources :timetables do
    resources :recipes, only: [:new, :create, :edit, :update, :destroy]
  end
  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :timetables
  has_many :recipes

  has_many :follower_relationships, foreign_key: :followee_id, class_name: 'Relationship', dependent: :destroy
  has_many :followee_relationships, foreign_key: :follower_id, class_name: 'Relationship', dependent: :destroy

  has_many :followers, through: :follower_relationships, source: :follower
  has_many :followees, through: :followee_relationships, source: :followee

  def follow(user)
    followee_relationships.create(followee_id: user.id)
  end

  def unfollow(user)
    followee_relationships.find_by(followee_id: user.id)&.destroy
  end

  def following?(user)
    followees.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @users = User.where.not(id: current_user.id)
  end
  def show
    @user = User.find(params[:id])
    @timetables = @user.timetables
  end

  def profile
    @user = User.find(params[:id])
    @followers = @user.followers
    @following = @user.followees
    @timetables = @user.timetables
    @users = User.where.not(id: current_user.id)

  end

  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
    redirect_to @user, notice: 'You are now following this user.'
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow(@user)
    redirect_to @user, notice: 'You have unfollowed this user.'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/follow.html.erb
<h1>Users#follow</h1>
<p>Find me in app/views/users/follow.html.erb</p>

app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.email, user_path(user) %> <!-- Change to user.name if you have a name attribute -->
    </li>
  <% end %>
</ul>

app/views/users/profile.html.erb
<div class="container mt-4">
  <h1><%= @user.email %>'s Profile</h1>
  <p>Followers: <%= @followers.count %> | Following: <%= @following.count %></p>

  <% if current_user != @user %>
    <% if current_user.following?(@user) %>
      <%= link_to "Unfollow", unfollow_user_path(@user), method: :post, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "Follow", follow_user_path(@user), method: :post, class: "btn btn-primary" %>
    <% end %>
  <% end %>

   <h2>Other Users</h2>
  <div class="container mt-4 mb-4">
    <ul class="list-group">
      <% @users.each do |other_user| %>
        <li class="list-group-item">
          <%= other_user.email %>
          <% if current_user != other_user %>
            <% if current_user.following?(other_user) %>
              <%= link_to "Unfollow", unfollow_user_path(other_user), method: :post, class: "btn btn-danger btn-sm float-end" %>
            <% else %>
              <%= link_to "Follow", follow_user_path(other_user), method: :post, class: "btn btn-primary btn-sm float-end" %>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

  <h2>Your Timetables</h2>
  <div class="container mt-4 mb-4">
    <table class="table table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>Type</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @timetables.each do |timetable| %>
          <tr>
            <td><%= timetable.time_range_type&.capitalize || 'Not specified' %></td> 
            <td>
              <% if timetable.time_range_type == "month" %>
                First of the Month 
              <% else %>
                <%= timetable.start_date&.strftime("%B %d, %Y") || 'Not specified' %>
              <% end %>
            </td>
            <td>
              <% if timetable.time_range_type == "month" %>
                End of the Month
              <% else %>
                <%= timetable.end_date&.strftime("%B %d, %Y") || 'Not specified' %>
              <% end %>
            </td>
            <td>
              <%= link_to 'Show', timetable_path(timetable), class: 'btn btn-info btn-sm' %>
              <%= link_to 'Edit', edit_timetable_path(timetable), class: 'btn btn-warning btn-sm' %>
              <%= link_to 'Destroy', timetable_path(timetable), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.email %></h1> <!-- Change to @user.name if you have a name attribute -->

<% if current_user.following?(@user) %>
  <%= button_to 'Unfollow', unfollow_user_path(@user), method: :delete, class: 'btn btn-danger' %>
<% else %>
  <%= button_to 'Follow', follow_user_path(@user), method: :post, class: 'btn btn-primary' %>
<% end %>

<h2>Followers</h2>
<ul>
  <% @user.followers.each do |follower| %>
    <li><%= link_to follower.email, user_path(follower) %></li> <!-- Change to follower.name if you have a name attribute -->
  <% end %>
</ul>

<h2>Following</h2>
<ul>
  <% @user.followees.each do |followee| %>
    <li><%= link_to followee.email, user_path(followee) %></li> <!-- Change to followee.name if you have a name attribute -->
  <% end %>
</ul>

app/views/users/unfollow.html.erb
<h1>Users#unfollow</h1>
<p>Find me in app/views/users/unfollow.html.erb</p>