config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'users/follow'
  get 'users/unfollow'
  get 'home/index'
  devise_for :users
  resources :users, only: [:index, :show] do
    member do
      post 'follow'
      delete 'unfollow'
      get 'profile'
    end
  end
  resources :timetables do
    resources :recipes, only: [:new, :create, :edit, :update, :destroy]
  end
  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodon</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Load jQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <!-- Preload CSS files -->
  <link rel="preload" href="<%= asset_path('application.css') %>" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <link rel="preload" href="<%= asset_path('custom.css') %>" as="style" onload="this.onload=null;this.rel='stylesheet'">

  <!-- Fallback for non-JS environments -->
  <noscript>
    <link rel="stylesheet" href="<%= asset_path('application.css') %>">
    <link rel="stylesheet" href="<%= asset_path('custom.css') %>">
  </noscript>

  <!-- Regular stylesheet links for Turbo links -->
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "custom", media: "all", data: { turbolinks: false } %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">SIMIZKITCHEN</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0"> <!-- Changed ml-auto to ms-auto for right alignment -->
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Timetables', timetables_path, class: 'nav-link' %>
          </li>
         <li class="nav-item">
            <%= link_to 'Profile', profile_user_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-1" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>


  <div class="container mt-5">
    <%= yield %>
      <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </div>
</body>
</html>